### ISSUE TITLE
Error while adding annotation SnpEff

### ISSUE THREAD

**Issue by Jemkon** [skandlab/SMuRF#20]
Hello,

I would like to try SMuRF to predict variants from BAM. 

Here what I run on test files.

    myresults <- smurf(mydir, "combined")

     Completed but with warning:

    Time difference of 15.69459 secs
     Warning messages:
     1: In FUN(X[[i]], ...) :
       duplicate ID's in header will be forced to unique rownames
    2: In FUN(X[[i]], ...) :
       duplicate ID's in header will be forced to unique rownames

    Then I run.....
    myresults <- smurf(mydir, "cdsannotation") 
     
     .....
    [1] "Predicting SNVs" 
    |======================================================================| 100% 
    |======================================================================| 100%
    
    [1] "Predicting INDELs"
    |======================================================================| 100% 
    |======================================================================| 100%
    
    [1] "SNV annotation"
    [1] "Adding CDS and annotations"
    [1] "reading mutect2"  
    Error in (function (classes, fdef, mtable)  : 
      unable to find an inherited method for function ?scanVcf? for signature ?"character", "GRanges"?
     In addition: Warning messages:
     1: In FUN(X[[i]], ...) :
       duplicate ID's in header will be forced to unique rownames
     2: In FUN(X[[i]], ...) :
       duplicate ID's in header will be forced to unique rownames

I would really like to get variants with annotations from SnpEff/SnpSift. How do i get it from SMuRF. Do I have to run SMuRF first and then save the output to vcf, which then parsed to SnpEff? 

Many thanks.

**Comment by tyler5huang** [comment]
Hi Jemkon, apologies, please have your .vcf files tabix indexed as the annotations require an indexed .tbi file. For example `tabix –p vcf *.vcf.gz` on the unix console, for the mutect2, vardict, varscan and freebayes vcf files. Thanks
