### ISSUE TITLE
error at or after formatting step

### ISSUE THREAD

**Issue by gianfilippo** [skandlab/SMuRF#40]
Hi,

I am afraid I am having another issue. An error at or after the formatting step. What do you think ?

My command line is 
myresults = smurf(directory="Sample_test", mode="combined", check.packages=T, t.label="T_")
the dir sample test contains the 4 required files

The output is below (reporting only the relevant part)
Accessing files:
Sample_test/mutect2.vcf.gz
Sample_test/freebayes.vcf.gz
Sample_test/varscan.vcf.gz
Sample_test/vardict.vcf.gz
[1] "Parsing step"
[1] "reading vcfs"
[1] "reading mutect2"
[1] "reading freebayes"
[1] "reading varscan"
[1] "reading vardict"
Time difference of 12.42901 secs
[1] "extracting calls passed by at least 1 caller"
Time difference of 0.7296524 secs
[1] "extracting meta data from VRanges"
Time difference of 3.151198 secs
[1] "merge 4 vcfs and meta data"
Time difference of 0.5899651 secs
[1] "formating"
Time difference of 0.7452195 secs
Error in `[.data.frame`(meta_data, , c("MQ_Mutect2", "MQRankSum_Mutect2",  :
  undefined columns selected

**Comment by tyler5huang** [comment]
Hi

May I know if the Sample_test files are the ones provided in the SMuRF package?

**Comment by gianfilippo** [comment]
Hi,

it works with your files, I just tested it. I will send you a link.

Thanks
Gianfilippo

**Comment by tyler5huang** [comment]
Issue resolved - SMuRFv1.6.4
