### ISSUE TITLE
Cannot install from source and no smurf() function

### ISSUE THREAD

**Issue by ferygood** [skandlab/SMuRF#55]
Hello, 

I am having two troubles using SmuRF.
(1) Cannot install from source: 
After downloading **SMuRFv2.0.10.tar.gz**, I faced `skipping pax global extended headers` installation problem. 

(2) could not find function "smurf"
I also tried using devtools::install_github() function to install smurf. It can be install but when I try to call smurf function, I get a error `Error in smurf() : could not find function "smurf"`

I am using RStudio and R 4.2 environment on macOS (Monterey)

Hope you can give me some suggestion and help. Thank you for your time!

**Comment by tyler5huang** [comment]
Hi this is due to a roxygen issue with package documentation, failed to install/read package correctly.

Please use the latest release of SMuRF: https://github.com/skandlab/SMuRF/releases/tag/SMuRFv2.0.11

**Comment by tyler5huang** [comment]
> devtools::install_github("skandlab/SMuRF", subdir="smurf")
Downloading GitHub repo skandlab/SMuRF@HEAD
√  checking for file 'C:\Users\huangwt\AppData\Local\Temp\Rtmpcn6JWZ\remotes45587b46ba1\skandlab-SMuRF-73b03fc\smurf/DESCRIPTION' ...
-  preparing 'smurf': (2.8s)
√  checking DESCRIPTION meta-information ... 
-  checking for LF line-endings in source and make files and shell scripts
-  checking for empty or unneeded directories
     NB: this package now depends on R (>= 3.5.0)
     WARNING: Added dependency on R >= 3.5.0 because serialized objects in
     serialize/load version 3 cannot be read in older versions of R.
     File(s) containing such objects:
       'smurf/data/cds-hg38.rds'
-  building 'smurf_2.0.tar.gz'

Installing package into ‘C:/Users/huangwt/Documents/R/win-library/4.1’
(as ‘lib’ is unspecified)
* installing *source* package 'smurf' ...
** using staged installation
** R
** data
*** moving datasets to lazyload DB
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
  converting help for package 'smurf'
    finding HTML links ... done
    CDSannotation_indel                     html  
    CDSannotation_snv                       html  
    indelRFpredict                          html  
    newcutoffs                              html  
    parsevcf_allfeaturesall                 html  
    read.vcf                                html  
    save.files                              html  
    smurf                                   html  
    snvRFpredict                            html  
** building package indices
** testing if installed package can be loaded from temporary location
*** arch - i386
*** arch - x64
** testing if installed package can be loaded from final location
*** arch - i386
*** arch - x64
** testing if installed package keeps a record of temporary installation path
* DONE (smurf)
> library(smurf)
> smurf()
[1] "SMuRFv2.0.11 (4th Jul 2022)"
smurf(directory=NULL, mode=NULL, nthreads = -1,
                 annotation=F, output.dir=NULL,  parse.dir=NULL,
                 snv.cutoff = 'default', indel.cutoff = 'default',
                 build=NULL, change.build=F, find.build=F,
                 t.label=NULL, re.tabIndex=F,
                 check.packages=T, file.exclude=NULL)

**Comment by ferygood** [comment]
Thank you for your response! `R CMD INSTALL SMuRFv2.0.11.tar.gz` cannot install facing 
`ERROR: cannot extract package from '/Users/yaochung41/Downloads/SMuRF-SMuRFv2.0.11.tar.gz'`

However, I have successfully install and use the function by first cloning github and than use `install.packages("SMuRF/smurf", repos=NULL, type="source"`
